### ISSUE TITLE
Crash on Android, works fine on iOS

### ISSUE THREAD

**Issue by anilios** [Saranshmalik/react-native-zendesk#17]
This is how I am using the setup. Keys etc are fine because tickets show up when using iOS. It is just on Android that app crashes as soon as the button tapped to call the code below.

`RNZendeskChat.init({
      key: ZenDeskConstants.accountKey,
      appId: ZenDeskConstants.appId,
      url: ZenDeskConstants.url,
      clientId: ZenDeskConstants.clientId,
    });
    RNZendeskChat.setVisitorInfo({
      name: "Test",
      email: "test@gmail.com",
    });
    RNZendeskChat.startChat({
      chatOnly: false,
      withChat: true,
      disableTicketCreation: false,
    });`

This is working on iOS fine but on Android, it just crashes. Can not see anything in logs also.
![1618021128237](https://user-images.githubusercontent.com/694814/114255154-3b7a0880-99d1-11eb-82d4-ba697d75775a.JPEG)

**Comment by Saranshmalik** [comment]
I don't see setUserIdentity method being called. That's required before you can use supportSDK. The error shows that only, missing name in setuseridentity. Make sure you do add that, will make it more clear and throw better errors for this.

**Comment by anilios** [comment]
Even after calling setUserIdentity, still getting the same user, tried the following:

`  RNZendeskChat.setUserIdentity({
      name: "John",
      email: "xyz@abc.com",
    });
    RNZendeskChat.startChat({
      chatOnly: false,
      withChat: true,
      disableTicketCreation: false,
    });`


But still gives name error for setUserIdentity.


Then i tried following and it worked:

  RNZendeskChat.setUserIdentity({
      name: "John",
      email: "xyz@abc.com",
    });
    RNZendeskChat.startChat({
      name: "John",
      email: "xyz@abc.com",
      chatOnly: false,
      withChat: true,
      disableTicketCreation: false,
      botName: "XYZ"
    });

In this case, the crash goes away, but the chatbot still keeps on asking name and email even though name and email is set. This is happening for both iOS and Android.

**Comment by Saranshmalik** [comment]
Probably a configuration issue. Working on a newer version with better config options to iron out such issues. For now, I'll think on if we have a temp solution for this

**Comment by anilios** [comment]
For now, I am happy that I have working code for iOS and Android. The library is working great with Ticket creations.
