### ISSUE TITLE
iOS: how to display chat list icons like Android

### ISSUE THREAD

**Issue by lekeCoder** [Saranshmalik/react-native-zendesk#18]
Help Center 

Android Screen:

![Screenshot_1618366523](https://user-images.githubusercontent.com/19432914/114644662-8f207680-9c9d-11eb-885d-d248d9ee25bf.png)

iOS Screen:

![simulator_screenshot_53494B48-898F-4C17-B71D-B2E0A4B6AAC1](https://user-images.githubusercontent.com/19432914/114644749-b9723400-9c9d-11eb-9f9a-3b2c62136a99.png)

**Comment by Saranshmalik** [comment]
@lekeCoder This library just gets a RN bridge, this is just how native SDKs of Zendesk work. I can't help on anything here.
