### ISSUE TITLE
Does the package handle push notifications ?

### ISSUE THREAD

**Issue by podotki** [Saranshmalik/react-native-zendesk#2]
Hi,

I just wanted to know if it is possible to handle push notifications with your package ?

Many thanks :)

**Comment by Saranshmalik** [comment]
Well, no I have that in my list, just not getting time to work upon it. I will update you with a timeline once I get some time.

**Comment by podotki** [comment]
Ok great ! Thanks buddy

**Comment by Saranshmalik** [comment]
@podotki I am going to add a method to register for notifications, handling notifications would have to be done on your end by whatever library you use. Adding in a new method `setNotificationToken`. Let me know if that helps you out.
