### ISSUE TITLE
[Help Center] no articles found

### ISSUE THREAD

**Issue by guangyu-moves** [Saranshmalik/react-native-zendesk#25]
Hello @Saranshmalik! Thanks for creating this package. I have a small issue with the Help Center.

I initialize a fresh repo with `react-native init` and tried both `Chat` and `Help Center`. While `Chat` started up, the `Help Center` showed `no articles found`

Have you came across this before? Logs are in the screenshot below. Thank you!

<img width="1377" alt="Screen Shot 2021-11-21 at 11 42 29 PM" src="https://user-images.githubusercontent.com/86622911/142802299-56bba27c-fac0-4ea8-9cfc-22880cca5872.png">

**Comment by guangyu-moves** [comment]
Oops, here is another screenshot showing `No articles found`. Sometimes it shows the other screenshot.

I have many articles in the `Zendesk Help Center`, and they are all set to `visible`.

<img width="317" alt="no articles found" src="https://user-images.githubusercontent.com/86622911/142802608-a9e6a53d-2809-4fb0-b5eb-7e92b96ea579.png">

**Comment by guangyu-moves** [comment]
Issue resolved.

Reason is that I cannot pass the same email for both the chat account and the anonymousIdentity. Not sure why, but this only affects iOS.

**Comment by MathisBarre** [comment]
@guangyu-moves we have the same issue as you. Can you elaborate ?

**Comment by guangyu-moves** [comment]
@MathisBarre It's been a while but I think I fixed my issue by using a different email for the chat account and the anonymousIdentity. I think it might have to do with [https://github.com/Saranshmalik/react-native-zendesk/blob/master/ios/RNZendeskChat.m#L67]( https://github.com/Saranshmalik/react-native-zendesk/blob/master/ios/RNZendeskChat.m#L67)

**Comment by fahadhaque007** [comment]
Anyone else who might run into this issue, need to set the identity 

`RNZendesk.setUserIdentity({email: email, name: name})`

I did that before calling showHelpCenter

`RNZendesk.showHelpCenter({
    withChat: true,
    chatOnly: false,
    name: name,
    email: email
  })`

**Comment by MathisBarre** [comment]
Honestly, this SDK is a mess, we ended up displaying web help center with a webview
