### ISSUE TITLE
Attempt to invoke virtual method 'zendesk.core.CoreModule zendesk.core.ZendeskShadow.coreModdule()' on a null object reference

### ISSUE THREAD

**Issue by victor-scaleforce** [Saranshmalik/react-native-zendesk#3]
This error "Attempt to invoke virtual method 'zendesk.core.CoreModule zendesk.core.ZendeskShadow.coreModdule()' on a null object reference" pops when calling .
    
ZendeskChat.startChat({
      name: 'test',
      email: 'test',
      phone: 'test',
      tags: ['tag1', 'tag2'],
      department: 'Your department',
      chatOnly: false,
      botName: 'bottest',
    });

**Comment by Saranshmalik** [comment]
Did you init with proper keys before using the startChat method? I tried and couldn't replicate it out.

**Comment by tinni95** [comment]
same here, react-native 0.63 and I called   RNZendeskChat.initChat(CHAT_ID); before

**Comment by Saranshmalik** [comment]
Could you like get me a demo app or something? I am unable to replicate this out.

**Comment by stewartmcgown** [comment]
`initChat` is broken in latest release, make sure you use `init` instead. Use the keys from the Mobile SDK section in Zendesk

**Comment by Saranshmalik** [comment]
I'll look over the initChat method

**Comment by Saranshmalik** [comment]
I see no issue initChat worked just fine, can you guys let me know what exactly is the issue you facing?

**Comment by stewartmcgown** [comment]
Did you also run .init in the same project? The issue is with projects that
do not call init.

**Comment by Saranshmalik** [comment]
Nope I replaced my init call with initChat and then used startChat, it connected with my zendesk chat and I could send and receive messages

**Comment by Saranshmalik** [comment]
Did you guys use chatOnly:true while using startChat function?

**Comment by stewartmcgown** [comment]
I did yeah 😕

**Comment by Saranshmalik** [comment]
Which RN version did you try on? Maybe some issues with RN versions.

**Comment by stewartmcgown** [comment]
0.63.3

**Comment by Saranshmalik** [comment]
I tried on the same too. And use the lib in a production app and never heard back of such crash. Will try investigate more, you recieve the exact error as the one mentioned?
