### ISSUE TITLE
ZendeskChat is undefined

### ISSUE THREAD

**Issue by hanaechahid** [Saranshmalik/react-native-zendesk#5]
```
ZendeskChat.startChat({
      chatOnly: true
    });
```
alwaus ZendeskChat / RNZendeskChat is undefined

**Comment by Saranshmalik** [comment]
There is a typo in Docs, ideally it should be `RNZendeskChat.startChat`. Also if it occurs with that too then, please provide some more info like which RN version you are using, have you imported the library properly and initialised it?

**Comment by hanaechahid** [comment]
hi @Saranshmalik , I have a question please, your plugin is react-native-zendesk-v2 so I installed why we imported from react-native-zendesk and not react-native-zendesk-v2? when I use react-native-zendesk-v2 I get new issue: 

> "Cannot read property 'startChat' of undefined"

so when I imported from react-native-zendesk, I get this: 

> bundling failed: Error: Unable to resolve module `react-native-zendesk` from `/App/Containers/Menu/ControlPanel.js`: Module `react-native-zendesk` does not exist in the Haste module map.

**environment**
     "react-native": "0.59.0",
    "react-native-zendesk-v2": "^0.2.1",

**Comment by Saranshmalik** [comment]
Okay the doc has some issues, my bad will fix those.
Please try this
`import RNZendesk from 'react-native-zendesk-v2'`

Also since you are on RN v0.59 make sure you follow the package linking as per RN docs.

**Comment by hanaechahid** [comment]
it works thank you @Saranshmalik
