### ISSUE TITLE
Url error

### ISSUE THREAD

**Issue by hanaechahid** [Saranshmalik/react-native-zendesk#6]
![Screenshot_20201130-141017_IZI Check](https://user-images.githubusercontent.com/25223093/100614587-a4ac8980-3316-11eb-9dda-98b0e0f4c5c0.jpg)
Hi @Saranshmalik , it works fine for ios but isnt in android

**Comment by Saranshmalik** [comment]
Feels like URL field is not being passed. Make sure the RNZendesk.init function has url key in it since its required. All the props in init function are required. If you just need chat functionality, use RNZendesk.initChat function instead

**Comment by hanaechahid** [comment]
but I didn't change the init function, is the same code as ios

**Comment by Saranshmalik** [comment]
Can you post it here?

**Comment by hanaechahid** [comment]
I initialize it in componentdidmount like this:
```
import RNZendesk from 'react-native-zendesk-v2'
componentDidMount(){
    RNZendesk.init({
      key: "key",
      appId: "appid",
      zendeskUrl:"url",
      clientId: "mobile_sdk_client"
    })
}
````

and here i start the chat in the same file: 
```
goToChat() {
    RNZendesk.startChat({
      name: this.props.currentUser.firstName,
      email: this.props.currentUser.mail,
      phone: this.props.currentUser.phone,
      tags: ['tags'],
      department: "Your department",
      chatOnly: true
    });
  }
```

**Comment by hanaechahid** [comment]
i unlink the library, but i get new issue "Cannot read property startChat of undefined" cause RNZendesk is undefined

**Comment by Saranshmalik** [comment]
You don't need to unlink the library, it will cause issues. Also the exact line says the url being passed is not a string and thus causing issues. Make sure the support url is correct and type is string

**Comment by hanaechahid** [comment]
if the url is not correct it should not be working on ios, as I said I made one initialization and one configuration in the same file for both ios and android so i dont think the problem is using wrong url

**Comment by hanaechahid** [comment]
I've made a mistake, I should use url instead of zendeskUrl while initialization

thank you for everything @Saranshmalik
