### ISSUE TITLE
how use notifications

### ISSUE THREAD

**Issue by hanaechahid** [Saranshmalik/react-native-zendesk#9]
Hi @Saranshmalik , it's always me ,but this time I need help to know how use notifications?
do you have any process?

**Comment by Saranshmalik** [comment]
Well the Zendesk package has the option to register notification token onto Zendesk to recieve chat notification. To generate a notification token and to handle/display notification you would have to look out for a dedicated library. We have loads like react native push notification or the firebase library has a way for that too. So you can generate and display notifications using that library and then register the token on Zendesk with the helper function of this library.

**Comment by Saranshmalik** [comment]
Also you would have to do some configuration for it on Zendesk admin panel too, you can check their docs for that
